<template>
  <div class="flex flex-col gap-8 p-4">
    <header class="flex flex-row items-center gap-4">
      <button
        class="btn btn-ghost"
        @click="onBackClick"
      >
        <BackIcon />
      </button>
      <TitleBar
        class="grow"
        :title="$t('Logs')"
      />
      <button
        class="btn btn-ghost"
        @click="onDownloadClick"
      >
        <PhDownloadSimple class="size-6" />
      </button>
    </header>
    <main class="flex grow flex-col gap-4">
      <p>
        Logs are generated by different components and pages of Mitika. If you faced any error, this
        can be a good place to investigate what went wrong. To report the issue to developers,
        please download the relevant logs and upload it to our <a class="link">issue tracker</a>.
      </p>
      <div class="flex flex-row flex-wrap gap-4">
        <label class="flex flex-row items-center gap-2">
          <input
            v-model="selectedLevels"
            class="checkbox checkbox-info"
            type="checkbox"
            :value="Level.Debug"
          />
          {{ $t("Debug") }}
        </label>
        <label class="flex flex-row items-center gap-2">
          <input
            v-model="selectedLevels"
            class="checkbox checkbox-success"
            type="checkbox"
            :value="Level.Info"
          />
          {{ $t("Info") }}
        </label>
        <label class="flex flex-row items-center gap-2">
          <input
            v-model="selectedLevels"
            class="checkbox checkbox-warning"
            type="checkbox"
            :value="Level.Warn"
          />
          {{ $t("Warn") }}
        </label>
        <label class="flex flex-row items-center gap-2">
          <input
            v-model="selectedLevels"
            class="checkbox checkbox-error"
            type="checkbox"
            :value="Level.Error"
          />
          {{ $t("Error") }}
        </label>
      </div>
      <ol class="flex flex-row flex-wrap gap-2 empty:hidden">
        <li v-for="domain of domains">
          <input
            v-model="selectedDomains"
            :aria-label="domain"
            class="btn"
            type="checkbox"
            :value="domain"
          />
        </li>
      </ol>
      <div class="flex flex-col overflow-scroll">
        <table class="table-zebra table-pin-rows table h-full">
          <thead>
            <tr>
              <th>
                {{ $t("Level") }}
              </th>
              <th>
                {{ $t("Domain") }}
              </th>
              <th>
                {{ $t("Message") }}
              </th>
            </tr>
          </thead>
          <tbody
            v-auto-animte
            class="font-mono"
          >
            <template v-if="reversedLogs.length != 0">
              <tr v-for="log in reversedLogs">
                <td>{{ log.level }}</td>
                <td>{{ log.domain }}</td>
                <td>{{ log.message }}</td>
              </tr>
            </template>
            <tr v-else>
              <td>-</td>
              <td>-</td>
              <td>
                {{
                  $t(
                    logs.length != 0
                      ? "Logs are empty. Try relaxing the filters."
                      : "Logs are empty.",
                  )
                }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</template>
<script setup lang="ts">
import { PhDownloadSimple } from "@phosphor-icons/vue";
import { Constants } from "@/constants";
import { Level, useLogs } from "@/logging";

const logs = useLogs();
const router = useRouter();

const domains = ref(new Set(logs.value.map((log) => log.domain).sort()));
const levels = ref(new Set([Level.Debug, Level.Info, Level.Warn, Level.Error]));
const selectedDomains = ref(new Set(domains.value));
const selectedLevels = ref(new Set(levels.value));

const filteredLogs = computed(() => {
  return logs.value.filter(
    (log) => selectedLevels.value.has(log.level) && selectedDomains.value.has(log.domain),
  );
});

const reversedLogs = computed(() => filteredLogs.value.reverse());

function onBackClick() {
  router.back();
}

function onDownloadClick() {
  const a = document.createElement("a");
  const url = URL.createObjectURL(
    new Blob([JSON.stringify(filteredLogs.value, null, 2)], { type: "application/json" }),
  );
  a.href = url;
  a.download = `${Constants.NAME}_logs.json`;
  a.click();
}

useHead({
  title: "Logs",
});
</script>
